project:
  type: book
  output-dir: _book

book:
  title: "टोटलाको फूल"
  author: "Mohit Shrestha"
  date: "8/2/2023"
  date-format: long
  search: true
  repo-url: "https://github.com/mohitshrestha/ebook_example"
  repo-actions: [edit]
  sharing: [twitter, facebook]
  downloads: [pdf, epub]
  page-navigation: true
  favicon: images/coverImage.jpeg
  twitter-card: true
  site-url: https://mohitshrestha.github.io/ebook_example/
  sidebar:
    style: docked
    background: light
  reader-mode: true
  # cover-image: images/coverImage.jpeg
  #cover-image-alt: |
  #  टोटलाको फूल Shrijana Gole Tamang Suman Maharjan
  chapters:
    - href: index.qmd
      text: "Cover Page"
    - href: page_1.qmd
      text: "Page: 1"
    - href: page_2.qmd
      text: "Page: 2"
    - href: page_3.qmd
      text: "Page: 3"
    - href: page_4.qmd
      text: "Page: 4"
    - href: page_5.qmd
      text: "Page: 5"
    - href: page_6.qmd
      text: "Page: 6"
    - href: page_7.qmd
      text: "Page: 7"
    - href: page_8.qmd
      text: "Page: 8"
    - href: page_9.qmd
      text: "Page: 9"
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
        light: cosmo
        dark: darkly
    css: css/epub.css
  pdf:
    keep-tex: true
    documentclass: scrreprt
    classoption: [paper=6in:9in,pagesize=pdftex,headinclude=on,footinclude=on,12pt]
    include-in-header:
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
        \areaset[0.50in]{4.5in}{8in}
    include-before-body:
      text: |
        \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
           showspaces = false,
           showtabs = false,
           breaksymbolleft={},
           breaklines
           % Note: setting commandchars=\\\{\} here will cause an error 
        }  
    fig-pos: 'H'
  epub:
    toc: true
    lang: en-US
    date: "8/2/2023"
    css: css/epub.css
    epub-cover-image: images/coverImage.jpeg

editor: visual



